services:

  generator:
    build:
      context: ./generator
    volumes:
      - hls-files:/hls
    environment:
      - TZ=UTC

  nginx:
    build:
      context: ./nginx
    ports:
      - "8081:80"
      - "8000:8000"
    volumes:
      - hls-files:/hls:ro
    environment:
      - TZ=UTC
    depends_on:
      - generator
    networks:
      - hls-dummy-streams-network

volumes:
  hls-files:

networks:
  hls-dummy-streams-network:
    driver: bridge
